
/**
 *
 * @author minec
 */
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result = new javax.swing.JTextField();
        clearAll = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        three = new javax.swing.JButton();
        two = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        openParentesis = new javax.swing.JButton();
        closeParentesis = new javax.swing.JButton();
        negation = new javax.swing.JButton();
        openParentesis1 = new javax.swing.JButton();
        one1 = new javax.swing.JButton();
        decimal1 = new javax.swing.JButton();
        seven1 = new javax.swing.JButton();
        four1 = new javax.swing.JButton();
        openParentesis2 = new javax.swing.JButton();
        one2 = new javax.swing.JButton();
        decimal2 = new javax.swing.JButton();
        seven2 = new javax.swing.JButton();
        four2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator By Group 1");
        setResizable(false);

        result.setEditable(false);
        result.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        result.setActionCommand("null");

        clearAll.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        clearAll.setText("CA");
        clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        delete.setText("Del");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        percent.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        percent.setText("%");
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        seven.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        eight.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        nine.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        four.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        five.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        six.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        one.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        three.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        two.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        decimal.setText(".");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        zero.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        divide.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        multiply.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        minus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        plus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorAction(evt);
            }
        });

        equals.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        openParentesis.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        openParentesis.setText("(");
        openParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        closeParentesis.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        closeParentesis.setText(")");
        closeParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPress(evt);
            }
        });

        negation.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        negation.setText("(-)");
        negation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negationAction(evt);
            }
        });

        openParentesis1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        openParentesis1.setText("==");
        openParentesis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openParentesis1buttonPress(evt);
            }
        });

        one1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        one1.setText("<");
        one1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one1buttonPress(evt);
            }
        });

        decimal1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        decimal1.setText(">");
        decimal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimal1buttonPress(evt);
            }
        });

        seven1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        seven1.setText("<=");
        seven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven1buttonPress(evt);
            }
        });

        four1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        four1.setText(">=");
        four1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four1buttonPress(evt);
            }
        });

        openParentesis2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        openParentesis2.setText("!=");
        openParentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openParentesis2buttonPress(evt);
            }
        });

        one2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        one2.setText("||");
        one2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one2buttonPress(evt);
            }
        });

        decimal2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        decimal2.setText("&&");
        decimal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimal2buttonPress(evt);
            }
        });

        seven2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        seven2.setText("=");
        seven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven2buttonPress(evt);
            }
        });

        four2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        four2.setText("!(");
        four2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four2buttonPress(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(openParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decimal2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(decimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(openParentesis1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(openParentesis2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearAll, closeParentesis, decimal, decimal1, decimal2, delete, divide, eight, equals, five, four, four1, four2, minus, multiply, negation, nine, one, one1, one2, openParentesis, openParentesis1, openParentesis2, percent, plus, seven, seven1, seven2, six, three, two, zero});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openParentesis2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openParentesis1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearAll, closeParentesis, decimal, decimal1, decimal2, delete, divide, eight, equals, five, four, four1, four2, minus, multiply, negation, nine, one, one1, one2, openParentesis, openParentesis1, openParentesis2, percent, plus, seven, seven1, seven2, six, three, two, zero});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(result.getText().equals(""))
            return;
        
        result.setText(result.getText().substring(0, result.getText().length()-1));
        
    }//GEN-LAST:event_deleteActionPerformed

    private String handleParentesis(String finalEquation){
        int startPos = -1, endPos = -1;
        for(int i = 0; i<finalEquation.length(); i++){
            if(startPos != -1 && endPos != -1)
                break;
            if(String.valueOf(finalEquation.charAt(i)).startsWith("("))
                startPos = i;
            else if (String.valueOf(finalEquation.charAt(i)).endsWith(")"))
                endPos = i;
        }
        String focus = finalEquation.substring(startPos+1, endPos);
        String result = evalEquation(focus);
        finalEquation = finalEquation.replace("("+focus+")", result);
        System.out.println(finalEquation);
        if(finalEquation.matches(".*\\(.*"))
            finalEquation = handleParentesis(finalEquation);
        return  finalEquation;
    }
    
    private String evalEquation(String finalEquation){
        List<String> equations = new ArrayList<>(Arrays.asList(finalEquation.split("(?<![\\d%])-?[\\d.%]+")));
        List<String> numbers = new ArrayList<>(Arrays.asList(finalEquation.split("(?<![\\+\\*\\/])\\-?(?<!^)\\-?[\\+\\-\\*\\/]")));
        equations.removeAll(Arrays.asList(""));
        numbers.replaceAll(e -> handlePercent(e));
        
        
        while(numbers.size() > 1){
            int mulPos = equations.indexOf("*");
            int divPos = equations.indexOf("/");
            int addPos = equations.indexOf("+");
            int subPos = equations.indexOf("-");
            int selPos = -1;
            Arithmetic selArithmetic = Arithmetic.ADD;

            if((divPos > -1 && mulPos == -1) || (divPos < mulPos && divPos != -1)){
                selPos = divPos;
                selArithmetic = Arithmetic.DIV;
            }else if((mulPos > -1 && divPos == -1) || (mulPos < divPos && mulPos != -1)){
                selPos = mulPos;
                selArithmetic = Arithmetic.MUL;                    
            }else if((addPos > -1 && subPos == -1) || (addPos < subPos && addPos != -1)){
                selPos = addPos;
                selArithmetic = Arithmetic.ADD;
            }else if((subPos > -1 && addPos == -1) || (subPos < addPos && subPos != -1)){
                selPos = subPos;
                selArithmetic = Arithmetic.SUB;
            }
            System.out.println(numbers);
            System.out.println(equations);
            numbers.set(selPos, String.valueOf(calculateEquation(selPos, numbers, selArithmetic)));
            System.out.println(numbers.get(selPos));

            equations.remove(selPos);
            numbers.remove(selPos+1);
        }
        return numbers.get(0);
    }
    
    private boolean isBalanced(String str){
        int i = 0;
        for(char s: str.toCharArray()){
            if(s == '(')
                i++;
            else if(s == ')')
                i--;
        }
        return i == 0;
    }
    
    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() instanceof javax.swing.JButton){
            String finalEquation = result.getText();
            System.out.println(finalEquation);

            if(finalEquation.matches(".*[\\+\\-\\*\\.\\/]+$")){
                deleteActionPerformed(evt);
            }

            while(!isBalanced(finalEquation)){
                finalEquation += ")";
            }

            if(finalEquation.matches(".*\\(.*")){
                finalEquation = handleParentesis(finalEquation);
            }
            String answer = evalEquation(finalEquation);
            
            DecimalFormat format = new DecimalFormat("0.#############");
            result.setText(format.format(Double.valueOf(answer)));
        }
    }//GEN-LAST:event_equalsActionPerformed

    private enum Arithmetic {ADD, SUB, MUL, DIV};
    
    private String handlePercent(String e){
        if(e.endsWith("%"))
            return String.valueOf(Double.parseDouble(e.substring(0, e.length()-1))/100);
        return e;
    }
    
    private Double calculateEquation(int pos, List<String> numbers, Arithmetic a ) {
        Double num1 = Double.valueOf(numbers.get(pos));
        Double num2 = Double.valueOf(numbers.get(pos+1));
        switch (a) {
            case MUL:
                return num1 * num2;
            case DIV:
                return num1 / num2;
            case ADD:
                return num1 + num2;
            case SUB:
                return num1 - num2;
            default:
                throw new AssertionError();
        }
    }
    
    private boolean validateButtonAction(javax.swing.JButton button){
            
        // handle illegal placement of numbers and decimals
        //  - Check if the last symbol isn't % or )
        if(result.getText().matches(".*[\\%\\)]$") && button.getText().matches("^[0-9\\.]$"))
            return false;

        // handle multiple decimals
        //  - Check if there isn't another decimal in the last number

        String lastNum = result.getText().replaceAll(".*[\\+\\-\\/\\*\\)]+", "");
        if(lastNum.matches(".*\\..*") && button.getText().equals("."))
            return false;

        // handle possible errors in close parentheses
        //  - Check if there there is an open parenthesis to close
        //  - Check if the last symbol in the equation isn't +, -, *, /, (
        if((isBalanced(result.getText()) || result.getText().matches(".*[\\+\\-\\*\\/\\(]$")) && button.getText().equals(")"))
            return false;

        // handle possible errors in percentage
        //  - Check if the last symbol ends isn't +, -, *, /, (, %
        if(result.getText().matches(".*[\\+\\-\\*\\/\\(\\%]$") && button.getText().equals("%"))
            return false;

        // handle possible errors in open parentheses
        //  - If the last symbol is a digit or ) then imply that it is multiplication
        if(result.getText().matches(".*(\\d|\\))$") && button.getText().equals("("))
            result.setText(result.getText().concat("*"));

        return true;
    }
        
    private void buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPress
        if(evt.getSource() instanceof javax.swing.JButton){
            javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
            if(validateButtonAction(button))
                result.setText(result.getText().concat(button.getText()));
        }
            
    }//GEN-LAST:event_buttonPress

    private void clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllActionPerformed
        // TODO add your handling code here:
        result.setText("");
    }//GEN-LAST:event_clearAllActionPerformed

    private void operatorAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorAction
        if(evt.getSource() instanceof javax.swing.JButton){
            javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
            String resultText = result.getText();
            String buttonText = button.getText();
            if(resultText.matches(".*\\([\\*\\-\\+\\/]*$") && !buttonText.equals("-"))
                return;
            if(resultText.matches(".*[\\+\\-\\*\\.\\/]+$"))
                deleteActionPerformed(evt);
            
            result.setText(resultText.concat(buttonText));
        }
    }//GEN-LAST:event_operatorAction

    private void negationAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negationAction
        // TODO add your handling code here:
        String lastNum = result.getText().replaceAll(".*[\\+\\/\\*]+", "");
        if (lastNum.isEmpty())
            return;
        String newEquation = result.getText().replaceAll("([\\d\\)]|\\(\\-)+$", "");
        if(lastNum.matches(".*\\(-[\\d\\.]+\\)$"))
            result.setText(newEquation.concat(lastNum.substring(2,lastNum.length()-1)));
        else if(lastNum.matches("[\\d\\.\\%]+$"))
            result.setText(newEquation.concat("(-").concat(lastNum).concat(")"));
    }//GEN-LAST:event_negationAction

    private void openParentesis1buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openParentesis1buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_openParentesis1buttonPress

    private void one1buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one1buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_one1buttonPress

    private void decimal1buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimal1buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_decimal1buttonPress

    private void seven1buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven1buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_seven1buttonPress

    private void four1buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four1buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_four1buttonPress

    private void openParentesis2buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openParentesis2buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_openParentesis2buttonPress

    private void one2buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one2buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_one2buttonPress

    private void decimal2buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimal2buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_decimal2buttonPress

    private void seven2buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven2buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_seven2buttonPress

    private void four2buttonPress(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four2buttonPress
        // TODO add your handling code here:
    }//GEN-LAST:event_four2buttonPress

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearAll;
    private javax.swing.JButton closeParentesis;
    private javax.swing.JButton decimal;
    private javax.swing.JButton decimal1;
    private javax.swing.JButton decimal2;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton four1;
    private javax.swing.JButton four2;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton negation;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton one1;
    private javax.swing.JButton one2;
    private javax.swing.JButton openParentesis;
    private javax.swing.JButton openParentesis1;
    private javax.swing.JButton openParentesis2;
    private javax.swing.JButton percent;
    private javax.swing.JButton plus;
    private javax.swing.JTextField result;
    private javax.swing.JButton seven;
    private javax.swing.JButton seven1;
    private javax.swing.JButton seven2;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
