
/**
 *
 * @author minec
 */
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        percent = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        equalsComparison = new javax.swing.JButton();
        closeParentesis = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        four = new javax.swing.JButton();
        greaterEquals = new javax.swing.JButton();
        or = new javax.swing.JButton();
        greaterThan = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        and = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        notEquals = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        three = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        openParentesis = new javax.swing.JButton();
        negation = new javax.swing.JButton();
        clearAll = new javax.swing.JButton();
        lessThan = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        not = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        bitwise = new javax.swing.JButton();
        five = new javax.swing.JButton();
        lessEquals = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        six = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        assignDiv = new javax.swing.JButton();
        assignment = new javax.swing.JButton();
        assignAdd = new javax.swing.JButton();
        assignMul = new javax.swing.JButton();
        assignMin = new javax.swing.JButton();
        assignMod = new javax.swing.JButton();
        addAdd = new javax.swing.JButton();
        minMin = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator By Group 1");
        setBackground(backgroundColor);
        setResizable(false);

        buttonPanel.setBackground(getBackground());
        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        percent.setBackground(operatorColor);
        percent.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        percent.setForeground(textColor);
        percent.setText("%");
        percent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        plus.setBackground(operatorColor);
        plus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        plus.setForeground(textColor);
        plus.setText("+");
        plus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        equalsComparison.setBackground(operatorColor);
        equalsComparison.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        equalsComparison.setForeground(textColor);
        equalsComparison.setText("==");
        equalsComparison.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        equalsComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        closeParentesis.setBackground(operatorColor);
        closeParentesis.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        closeParentesis.setForeground(textColor);
        closeParentesis.setText(")");
        closeParentesis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        two.setBackground(numColor);
        two.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        two.setForeground(textColor);
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        one.setBackground(numColor);
        one.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        one.setForeground(textColor);
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        equals.setBackground(equalColor);
        equals.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        equals.setForeground(textColor);
        equals.setText("=");
        equals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        multiply.setBackground(operatorColor);
        multiply.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        multiply.setForeground(textColor);
        multiply.setText("*");
        multiply.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        four.setBackground(numColor);
        four.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        four.setForeground(textColor);
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        greaterEquals.setBackground(operatorColor);
        greaterEquals.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        greaterEquals.setForeground(textColor);
        greaterEquals.setText(">=");
        greaterEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        greaterEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        or.setBackground(operatorColor);
        or.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        or.setForeground(textColor);
        or.setText("||");
        or.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        greaterThan.setBackground(operatorColor);
        greaterThan.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        greaterThan.setForeground(textColor);
        greaterThan.setText(">");
        greaterThan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        greaterThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        seven.setBackground(numColor);
        seven.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        seven.setForeground(textColor);
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        and.setBackground(operatorColor);
        and.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        and.setForeground(textColor);
        and.setText("&&");
        and.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        decimal.setBackground(numColor);
        decimal.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        decimal.setForeground(textColor);
        decimal.setText(".");
        decimal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        notEquals.setBackground(operatorColor);
        notEquals.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        notEquals.setForeground(textColor);
        notEquals.setText("!=");
        notEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        delete.setBackground(clearColor);
        delete.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        delete.setForeground(textColor);
        delete.setText("Del");
        delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        three.setBackground(numColor);
        three.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        three.setForeground(textColor);
        three.setText("3");
        three.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        minus.setBackground(operatorColor);
        minus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        minus.setForeground(textColor);
        minus.setText("-");
        minus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        openParentesis.setBackground(operatorColor);
        openParentesis.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        openParentesis.setForeground(textColor);
        openParentesis.setText("(");
        openParentesis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        openParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        negation.setBackground(numColor);
        negation.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        negation.setForeground(textColor);
        negation.setText("(-)");
        negation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        negation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negationAction(evt);
            }
        });

        clearAll.setBackground(clearColor);
        clearAll.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        clearAll.setForeground(textColor);
        clearAll.setText("CA");
        clearAll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllActionPerformed(evt);
            }
        });

        lessThan.setBackground(operatorColor);
        lessThan.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lessThan.setForeground(textColor);
        lessThan.setText("<");
        lessThan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lessThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        zero.setBackground(numColor);
        zero.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        zero.setForeground(textColor);
        zero.setText("0");
        zero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        not.setBackground(operatorColor);
        not.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        not.setForeground(textColor);
        not.setText("!(");
        not.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        divide.setBackground(operatorColor);
        divide.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        divide.setForeground(textColor);
        divide.setText("/");
        divide.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        bitwise.setBackground(operatorColor);
        bitwise.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        bitwise.setForeground(textColor);
        bitwise.setText("^");
        bitwise.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bitwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        five.setBackground(numColor);
        five.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        five.setForeground(textColor);
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        lessEquals.setBackground(operatorColor);
        lessEquals.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lessEquals.setForeground(textColor);
        lessEquals.setText("<=");
        lessEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lessEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        nine.setBackground(numColor);
        nine.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        nine.setForeground(textColor);
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        six.setBackground(numColor);
        six.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        six.setForeground(textColor);
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        eight.setBackground(numColor);
        eight.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        eight.setForeground(textColor);
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignDiv.setBackground(operatorColor);
        assignDiv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignDiv.setForeground(textColor);
        assignDiv.setText("/=");
        assignDiv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignment.setBackground(operatorColor);
        assignment.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignment.setForeground(textColor);
        assignment.setText("=");
        assignment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignAdd.setBackground(operatorColor);
        assignAdd.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignAdd.setForeground(textColor);
        assignAdd.setText("+=");
        assignAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignMul.setBackground(operatorColor);
        assignMul.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignMul.setForeground(textColor);
        assignMul.setText("*=");
        assignMul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignMin.setBackground(operatorColor);
        assignMin.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignMin.setForeground(textColor);
        assignMin.setText("-=");
        assignMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        assignMod.setBackground(operatorColor);
        assignMod.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignMod.setForeground(textColor);
        assignMod.setText("%=");
        assignMod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        addAdd.setBackground(operatorColor);
        addAdd.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        addAdd.setForeground(textColor);
        addAdd.setText("++");
        addAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        minMin.setBackground(operatorColor);
        minMin.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        minMin.setForeground(textColor);
        minMin.setText("--");
        minMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assignDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(assignMod, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minMin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignMul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignment, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignMin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(greaterEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(greaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(lessEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(equalsComparison, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(notEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(bitwise, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(openParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(closeParentesis, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addAdd, and, assignAdd, assignDiv, assignMin, assignMod, assignMul, assignment, bitwise, closeParentesis, decimal, divide, eight, equals, equalsComparison, five, four, greaterEquals, greaterThan, lessEquals, lessThan, minMin, minus, multiply, negation, nine, not, notEquals, one, openParentesis, or, percent, plus, seven, six, three, two, zero});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bitwise, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignMul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsComparison, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greaterEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignment, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignMod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addAdd, and, assignAdd, assignDiv, assignMin, assignMod, assignMul, assignment, bitwise, clearAll, closeParentesis, decimal, delete, divide, eight, equals, equalsComparison, five, four, greaterEquals, greaterThan, lessEquals, lessThan, minMin, minus, multiply, negation, nine, not, notEquals, one, openParentesis, or, percent, plus, seven, six, three, two, zero});

        getContentPane().add(buttonPanel, java.awt.BorderLayout.CENTER);

        resultPanel.setBackground(getBackground());

        result.setBackground(backgroundColor);
        result.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        result.setForeground(textColor);
        result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        result.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        result.setCaretColor(new java.awt.Color(0, 255, 153));
        result.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(resultPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllActionPerformed
        // TODO add your handling code here:
        result.setText("");
    }//GEN-LAST:event_clearAllActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int endModifier = 1;
        if(result.getText().equals(""))
            return;
        if(result.getText().matches(".*([\\+\\-\\*\\/\\<\\>\\=\\!]=|\\+\\+|\\-\\-|\\|\\||\\&\\&|\\!\\()$"))
            endModifier = 2;
        
        if(result.getText().matches(".*true$"))
            endModifier = 4;
        
        if(result.getText().matches(".*false"))
            endModifier = 5;
        

        result.setText(result.getText().substring(0, result.getText().length()-endModifier));
    }//GEN-LAST:event_deleteActionPerformed

    private String cleanEquation(String finalEquation) throws LogicalFormatException, InvalidEquationException{
        // remove trailing operators and spaces.
        finalEquation = finalEquation.replaceAll("(?!\\+\\+|\\-\\-)[^\\w\\)\\.]+$(?<!\\+\\+|\\-\\-)| ", "");

        // fix all parenthesis
        finalEquation = finalEquation.replaceAll("(?<=[\\w\\)])\\(", "*(");
        finalEquation = finalEquation.replaceAll("\\)(?=[\\w])", ")*");

        // add closing parenthesis
        while(!isBalanced(finalEquation)){
            finalEquation += ")";
        }

        if(finalEquation.matches(".*\\(.+")){
            finalEquation = handleParenthesis(finalEquation);
        }
        return finalEquation;
    }
    
    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() instanceof javax.swing.JButton){
            String finalEquation = result.getText();
            String answer = "";
            
            if(finalEquation.isEmpty()){
                return;
            }
            System.out.println(finalEquation);

            try{
                finalEquation = cleanEquation(finalEquation);
                
                answer = evalEquation(finalEquation);
                result.setText(format.format(Double.valueOf(answer)));
            } catch(NumberFormatException e) { // if the result is true or false
                result.setText(answer);
            } catch (InvalidEquationException | ArithmeticException | LogicalFormatException| NoSuchVariableException e){
                showErrorDialog(e.getMessage());
                result.setText("");
            }
        }
    }//GEN-LAST:event_equalsActionPerformed

    private void buttonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction
        // TODO add your handling code here:
        if(!(evt.getSource() instanceof javax.swing.JButton))
            return;
        
        javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
        
        if(button.getText().matches("\\d") && result.getText().matches("(true|false)"))
            result.setText("");
        
        result.setText(result.getText() + button.getText());
        
        
    }//GEN-LAST:event_buttonAction

    private void negationAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negationAction
        String[] numbers = result.getText().split("(?!^-)(?!(?<=[\\W])-)[^\\d\\.\\w\\s]");
        if (numbers.length == 0)
            return;
        String lastNum = numbers[numbers.length - 1];
        String newEquation = result.getText().replaceAll("(?<![\\w\\)\\ ])(\\(?\\-)?[\\w\\.]+\\)?(?=\\)*$)(?![\\w\\.]+)", "");
        if(lastNum.matches("\\(?-[\\w\\.]+\\)?$"))
            result.setText(newEquation.concat(lastNum.replaceAll("[\\(\\-\\)]", "")));
        else if(lastNum.matches("[\\w\\.]+$"))
            result.setText(newEquation.concat("(-").concat(lastNum).concat(")"));
    }//GEN-LAST:event_negationAction

    private void showErrorDialog(String e){
        JOptionPane.showMessageDialog(this, e, "Error Message", JOptionPane.ERROR_MESSAGE);
    }
    private String handleParenthesis(String finalEquation) throws LogicalFormatException{
        int startPos = -1, endPos = -1;
        for(int i = 0; i<finalEquation.length(); i++){
            if(startPos != -1 && endPos != -1)
                break;
            if(String.valueOf(finalEquation.charAt(i)).startsWith("("))
                startPos = i;
            else if (String.valueOf(finalEquation.charAt(i)).endsWith(")"))
                endPos = i;
        }
        
        String startParenthesis = "(";
        String focus = finalEquation.substring(startPos+1, endPos);
        String resultEquation;
        try {
            resultEquation = evalEquation(focus);
        } catch (InvalidEquationException | ArithmeticException | NoSuchVariableException e) {
            showErrorDialog(e.getMessage());
            return "";            
        }
        
        if(startPos > 0 && finalEquation.charAt(startPos-1) == '!'){
            if(!resultEquation.matches("true|false"))
                throw new LogicalFormatException();
            startParenthesis = "!" + startParenthesis;
            resultEquation = String.valueOf(!Boolean.valueOf(resultEquation));
        }
        finalEquation = finalEquation.replace(startParenthesis.concat(focus).concat(")"), resultEquation);
        System.out.println(finalEquation);
        if(finalEquation.matches(".*\\(.*"))
            finalEquation = handleParenthesis(finalEquation);
        return  finalEquation;
    }
    
    private String handleVariables(String var) throws ArithmeticException{
        int startPos = 0;
        int negate = 1;
        if(var.matches("^-.+$")){
            startPos = 1;
            negate = -1;
        }
        
        String varValue = variables.get(var.substring(startPos));
        try {
            if(varValue != null && varValue.matches("^(true|false)$") && negate == 1)
                return varValue;
            if(varValue != null)
                return String.valueOf(Double.parseDouble(varValue) * negate);
        } catch (NumberFormatException ex){
            throw new ArithmeticException();
        }
        return var;
    }
   
    
    private String evalEquation(String finalEquation) throws InvalidEquationException, ArithmeticException, NoSuchVariableException{
//        List<String> equations = new ArrayList<>(Arrays.asList(finalEquation.split("(?<![\\d])\\-?[\\d\\.\\w\\s]+")));
        List<String> operatorList = new ArrayList<>(Arrays.asList(finalEquation.split("(?<![\\w\\) ])\\-?[\\w.]+")));
        List<String> numbersList = new ArrayList<>(Arrays.asList(finalEquation.split("(?!^-)(?!(?<=[\\W])-)[^\\.\\w\\s]")));
        
        operatorList.removeAll(Arrays.asList(""));
        numbersList.removeAll(Arrays.asList(""));

        numbersList.replaceAll(e -> e.replaceAll("\\.0*$", ""));
        
        if(numbersList.isEmpty())
            return "";
        
        
        //Handle operations 
        do{
            if(numbersList.size() == 1 && (operatorList.isEmpty() || !operatorList.get(0).matches("^(\\+\\+|\\-\\-)$")))
                break;
            // TODO: Improve this part. Make a fuction that returms a list of operation order
            int mulPos = operatorList.indexOf("*");
            int divPos = operatorList.indexOf("/");
            int addPos = operatorList.indexOf("+");
            int subPos = operatorList.indexOf("-");
            int modPos = operatorList.indexOf("%");
            int gtPos = operatorList.indexOf(">");
            int ltPos = operatorList.indexOf("<");
            int gePos = operatorList.indexOf(">=");
            int lePos = operatorList.indexOf("<=");
            int eqPos = operatorList.indexOf("==");
            int nePos = operatorList.indexOf("!=");
            int orPos = operatorList.indexOf("||");
            int btPos = operatorList.indexOf("^");
            int adPos = operatorList.indexOf("&&");
            int aaPos = operatorList.indexOf("++");
            int mmPos = operatorList.indexOf("--");
            
            int selPos = -1;
            boolean removeSecondTerm = true;
            Operators selOperator = null;

            if(divPos > -1 && (divPos < mulPos || mulPos == -1) && (divPos < modPos || modPos == -1)){
                selPos = divPos;
                selOperator = Operators.DIV;
                
            } else if(mulPos > -1 && (mulPos < divPos || divPos == -1) && (mulPos < modPos || modPos == -1)){
                selPos = mulPos;
                selOperator = Operators.MUL;
                
            } else if(modPos > -1 && (modPos < divPos || divPos == -1) && (modPos < mulPos || mulPos == -1)){
                selPos = modPos;
                selOperator = Operators.MOD;
                
            } else if(addPos > -1 && (addPos < subPos || subPos == -1)){
                selPos = addPos;
                selOperator = Operators.ADD;
                
            } else if(subPos > -1 && (subPos < addPos || addPos == -1)){
                selPos = subPos;
                selOperator = Operators.SUB;
                
            } else if (gtPos > -1){
                selPos = gtPos;
                selOperator = Operators.GT;

            } else if (ltPos > -1){
                selPos = ltPos;
                selOperator = Operators.LT;

            } else if (gePos > -1){
                selPos = gePos;
                selOperator = Operators.GE;

            } else if (lePos > -1){
                selPos = lePos;
                selOperator = Operators.LE;

            } else if (eqPos > -1){
                selPos = eqPos;
                selOperator = Operators.ET;

            } else if (nePos > -1){
                selPos = nePos;
                selOperator = Operators.NET;
                
            } else if (adPos > -1){
                selPos = adPos;
                selOperator = Operators.AND;

            } else if (btPos > -1){
                selPos = btPos;
                selOperator = Operators.BIT;

            } else if (orPos > -1){
                selPos = orPos;
                selOperator = Operators.OR;
                
            } else if (aaPos > -1){
                selPos = aaPos;
                selOperator = Operators.PPLUS;
                removeSecondTerm = false;

            } else if (mmPos > -1){
                selPos = mmPos;
                selOperator = Operators.MMINUS;
                removeSecondTerm = false;
                
            } else if (operatorList.get(0).equals("=")){
                selOperator = Operators.ASSIGN;

            } else if (operatorList.get(0).equals("+=")){
                selOperator = Operators.AADD;

            } else if (operatorList.get(0).equals("-=")){
                selOperator = Operators.ASUB;
                
            } else if (operatorList.get(0).equals("*=")){
                selOperator = Operators.AMUL;

            } else if (operatorList.get(0).equals("/=")){
                selOperator = Operators.ADIV;

            } else if (operatorList.get(0).equals("%=")){
                selOperator = Operators.AMOD;

            } else {
                throw  new InvalidEquationException();
            }
            
            
            if(selOperator.ordinal() > 13 && selPos == -1)
                selPos = 0;
            
            System.out.println(numbersList);
            System.out.println(operatorList);
            try {
                numbersList.set(selPos, calculateEquation(numbersList, selPos, selOperator));
            } catch (NoSuchVariableException | ArithmeticException | LogicalFormatException | InequalityFormatException | InvalidNameException e) {
                showErrorDialog(e.getMessage());

                return "";
            }
            
//            if(selOperator.ordinal() > 13)
//                break;
            
            operatorList.remove(selPos);
            if(removeSecondTerm)
                numbersList.remove(selPos+1);
        }while(numbersList.size() > 1);
//       

        return handleVariables(numbersList.get(0));
    }
    
    private boolean isBalanced(String str) throws InvalidEquationException{
        int i = 0;
        for(char s: str.toCharArray()){
            if(s == '(')
                i++;
            else if(s == ')')
                i--;
        }
        if(i < 0)
            throw new InvalidEquationException();
        return i == 0;
    }
    
    private enum Operators {
        ADD,    // + Addition
        SUB,    // - Subtraction
        MUL,    // * Multiplication
        DIV,    // / Division
        MOD,    // % Modulus
        LT,     // < Less than
        GT,     // > Greater than
        LE,     // <= Less than or Equals to
        GE,     // >= Greater than or Equals to
        ET,     // == Equals to
        NET,    // != Not Equals to
        OR,     // || Logical OR
        AND,    // && Logical AND
        BIT,    // ^ Logical Bitwise
                // !( Not operator is handle on handle parenthesis
        ASSIGN, // = Assignment
        AADD,   // += Assign Add
        ASUB,   // += Assign Subtract
        AMUL,   // *= Assign Multiply
        ADIV,   // /= Assign Divided
        AMOD,   // %= Assign Modulus
        PPLUS,  // ++ add one to variable
        MMINUS, // -- minus one to variable
    };
    
    
    class NoSuchVariableException extends Exception{

        public NoSuchVariableException() {
            super("Variable does not Exists");
        }

    }
    
    class ArithmeticException extends Exception{

        public ArithmeticException() {
            super("Atemptted to do arithmetic operation on a non double");
        }
        
        public ArithmeticException(String e) {
            super(e);
        }

    }
    
    class LogicalFormatException extends Exception{

        public LogicalFormatException() {
            super("Atemptted to do logical operation on a non boolean");
        }

    }
    
    class InequalityFormatException extends Exception{

        public InequalityFormatException() {
            super("Atemptted to do inequality operation on a non digit");
        }

    }
    
    class InvalidEquationException extends Exception{

        public InvalidEquationException() {
            super("Invalid Equation");
        }

    }
    
    class InvalidNameException extends Exception{

        public InvalidNameException() {
            super("Bad variable name");
        }

    }
    
    
    private String calculateEquation(List<String> numbersList, int selPos, Operators a) 
            throws NoSuchVariableException, ArithmeticException, LogicalFormatException, InequalityFormatException, InvalidNameException{
        
        String num1 = numbersList.get(selPos);
        String num2 = "";

        if(!a.toString().matches("PPLUS|MMINUS"))
            num2 = numbersList.get(selPos+1);
        
        // If the second number is a variable; convert to its value; else return the usual value
        // If the usual value is a non Digit after the conversion; the variable does not exists
        num2 = handleVariables(num2);
        if(num2.matches("^(?!^(true|false)$)(?!^[^a-zA-Z_])\\w+$"))
            throw new NoSuchVariableException();
        //on assignment operator (=)
        if(a.ordinal() == 14){
            if(!num1.matches("^(?!^(true|false)$)(?!^[^a-zA-Z_])\\w+$"))
                throw new InvalidNameException();
        }
        
        //before assignment operator (=)
        if(a.ordinal() < 14){
            num1 = handleVariables(num1);
            
            if(num1.matches("^(?!^(true|false)$)\\D+$"))
                throw new NoSuchVariableException();
        }
        
        // On arithimetic operators (+, -, *, /, %)
        if(a.ordinal() < 5 && (num1.matches("^(true|false)$") || num2.matches("^(true|false)$")))
            throw new ArithmeticException();
        
        // On relational operators (>, <, >=, <=, ==, !=)
        if(a.ordinal() > 4 && a.ordinal() < 9 && (num1.matches("^(true|false)$") || num2.matches("^(true|false)$")))
            throw new InequalityFormatException();
        
        // On logical operators (||, &&, ^)
        if(a.ordinal() > 10 && a.ordinal() < 14 && (!num1.matches("^(true|false)$") || !num2.matches("^(true|false)$")))
            throw new LogicalFormatException();
        

        

        Double varNum = null;
        
        // after assignment operator (=)
        if(a.ordinal() > 14){
            try {
                varNum = Double.valueOf(variables.get(num1));
            } catch (NumberFormatException e) {
                throw new ArithmeticException();
            } catch (NullPointerException e) {
                throw new NoSuchVariableException();
            }
        }
        
        switch (a) {
            case MUL:
                return String.valueOf(Double.valueOf(num1) * Double.valueOf(num2));
            case DIV:
                if(num2.equals("0")) throw new ArithmeticException("Attempted to divide by zero");
                return String.valueOf(Double.valueOf(num1) / Double.valueOf(num2));
            case ADD:
                return String.valueOf(Double.valueOf(num1) + Double.valueOf(num2));
            case SUB:
                return String.valueOf(Double.valueOf(num1) - Double.valueOf(num2));
            case MOD:
                if(num2.equals("0")) throw new ArithmeticException("Attempted to divide by zero");
                return String.valueOf(Double.valueOf(num1) % Double.valueOf(num2));
            case LT:
                return String.valueOf(Double.valueOf(num1) < Double.valueOf(num2));
            case GT:
                return String.valueOf(Double.valueOf(num1) > Double.valueOf(num2));
            case LE:
                return String.valueOf(Double.valueOf(num1) <= Double.valueOf(num2));
            case GE:
                return String.valueOf(Double.valueOf(num1) >= Double.valueOf(num2));
            case ET:
                return String.valueOf(num1.equals(num2));
            case NET:
                return String.valueOf(!num1.equals(num2));
            case OR:
                return String.valueOf(Boolean.valueOf(num1) || Boolean.valueOf(num2));
            case AND:
                return String.valueOf(Boolean.valueOf(num1) && Boolean.valueOf(num2));
            case BIT:
                return String.valueOf(Boolean.valueOf(num1) ^ Boolean.valueOf(num2));
            case ASSIGN:
                variables.put(num1, num2);
                break;
            case AADD:
                variables.put(num1, format.format(varNum + Double.valueOf(num2)));
                break;
            case ASUB:
                variables.put(num1, format.format(varNum - Double.valueOf(num2)));
                break;
            case AMUL:
                variables.put(num1, format.format(varNum * Double.valueOf(num2)));
                break;
            case ADIV:
                variables.put(num1, format.format(varNum / Double.valueOf(num2)));
                break;
            case AMOD:
                variables.put(num1, format.format(varNum % Double.valueOf(num2)));
                break;
            case PPLUS:
                return format.format(varNum + 1);
            case MMINUS:
                return format.format(varNum - 1);
            default:
                throw new AssertionError();
        }

        return "";
    }
    
    
        
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }
    
    
    private final HashMap<String, String> variables = new HashMap<>();
    private final DecimalFormat format = new DecimalFormat("0.#############");

    
    private final java.awt.Color numColor = new java.awt.Color(57, 72, 103);
    private final java.awt.Color operatorColor = new java.awt.Color(33, 42, 62);
    private final java.awt.Color equalColor = new java.awt.Color(230, 57, 70);
    private final java.awt.Color backgroundColor = new java.awt.Color(29, 53, 87);
    private final java.awt.Color clearColor = new java.awt.Color(69, 123, 157);
    private final java.awt.Color textColor =  new java.awt.Color(241, 246, 249);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdd;
    private javax.swing.JButton and;
    private javax.swing.JButton assignAdd;
    private javax.swing.JButton assignDiv;
    private javax.swing.JButton assignMin;
    private javax.swing.JButton assignMod;
    private javax.swing.JButton assignMul;
    private javax.swing.JButton assignment;
    private javax.swing.JButton bitwise;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearAll;
    private javax.swing.JButton closeParentesis;
    private javax.swing.JButton decimal;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton equalsComparison;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton greaterEquals;
    private javax.swing.JButton greaterThan;
    private javax.swing.JButton lessEquals;
    private javax.swing.JButton lessThan;
    private javax.swing.JButton minMin;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton negation;
    private javax.swing.JButton nine;
    private javax.swing.JButton not;
    private javax.swing.JButton notEquals;
    private javax.swing.JButton one;
    private javax.swing.JButton openParentesis;
    private javax.swing.JButton or;
    private javax.swing.JButton percent;
    private javax.swing.JButton plus;
    private javax.swing.JTextField result;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}